name: Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Running tests
        # env:
        #   RPC_ENDPOINT: ${{ secrets.RPC_ENDPOINT }}
        run: npm run test
